CREATE OR REPLACE TRIGGER USERS_INSERT_T1
BEFORE INSERT ON users FOR EACH ROW
BEGIN
	IF @trigger_flag IS NULL THEN
		SET @trigger_flag = 1;
		SET NEW.CREATION_DATE=SYSDATE();
    	SET NEW.LAST_UPDATE_DATE=SYSDATE();
    END IF;
END;

	

CREATE OR REPLACE TRIGGER USERS_UPDATE_T2
BEFORE UPDATE ON users FOR EACH ROW
BEGIN
	IF @trigger_flag IS NULL THEN
		SET @trigger_flag = 1;
		SET NEW.LAST_UPDATE_DATE=SYSDATE();
    END IF;
END;